version: '3.8'

services:
  postgres_db:
    image: postgres:15 
    container_name: holoclean_postgres_db
    environment:
      POSTGRES_DB: holoclean_db
      POSTGRES_USER: holoclean_user
      POSTGRES_PASSWORD: holoclean_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    
volumes:
  postgres_data: